"""Time-and-materials invoice + payroll workbook from a work log.

Sheets
------
Invoice    printable A4 invoice: one line per specialist (billed hours x rate), tax, total,
           hours by project, cross-check; print area and page setup are set
Payroll    hours worked, pay, adjustments (input), billed amount, margin, utilisation
Summary    week-by-week summary of the chosen date range (+ chart)
WorkLog    the time log as an Excel Table with calculated columns
           (ROUNDUP to the billing increment, rate lookups, amounts, cost)
Rates      rates table (bill rate for the client, pay rate for the employee) - inputs
Settings   invoice number, dates, period, payment terms, increment, tax, parties

All totals are SUMIFS over tblLog limited to the period on the Settings sheet.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta
from pathlib import Path

from openpyxl import Workbook
from openpyxl.chart import BarChart, Reference
from openpyxl.formatting.rule import FormulaRule
from openpyxl.styles import Alignment, Border, Font, Side
from openpyxl.workbook.defined_name import DefinedName
from openpyxl.workbook.properties import CalcProperties
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.worksheet.table import Table, TableFormula, TableStyleInfo

from . import DEMO_CLIENT, DEMO_CONTRACTOR
from .formulas import date_text, quote_sheet
from .style import (BAD, BLUE, GOOD, HEADER_FILL, INK_2, MUTED, ORANGE, PANEL, TOP_DOUBLE,
                    base_sheet, body_cell, fill, font, header_row, input_cell, section_title,
                    set_widths, style_bar_chart, title_bar)
from .worklog import Rate, WorkEntry

LOG = "tblLog"
RATES = "tblRates"
WEEKS = 6
FMT_MONEY = '#,##0.00;-#,##0.00;"–"'
FMT_H = '#,##0.00;-#,##0.00;"–"'
FMT_PCT = '0%;-0%;"–"'

L10N = {
    "en": {
        "sheets": {"invoice": "Invoice", "payroll": "Payroll", "summary": "Summary",
                   "log": "WorkLog", "rates": "Rates", "settings": "Settings"},
        "log_cols": ["Date", "Employee", "Project", "Task", "Hours", "Billable", "BilledHours",
                     "BillRate", "Amount", "PayRate", "Cost"],
        "rate_cols": ["Employee", "Role", "BillRate", "PayRate"],
        "yes": "Yes", "no": "No",
        "date_fmt": "yyyy-mm-dd",
        "demo": "Demo project · Демо-проект — companies, people and figures are fictional",
        "settings_title": "Invoice & payroll settings",
        "set_hdr": ["Parameter", "Value", "Note"],
        "set_rows": [
            ("invNo", "Invoice No.", "Printed on the invoice"),
            ("invDate", "Invoice date", ""),
            ("perFrom", "Period from", "Only log rows inside the period are billed / paid"),
            ("perTo", "Period to", "Inclusive"),
            ("termsDays", "Payment terms, days", "Due date = invoice date + terms"),
            ("billInc", "Billing increment, h", "Each time entry is rounded UP to this step (0.25 = 15 min)"),
            ("taxRate", "Tax / VAT rate", "0% if not applicable"),
            ("currency", "Currency", "Used in column headers"),
        ],
        "parties": [
            ("ctrName", "Contractor", "Contractor name"),
            ("ctrAddr", "Contractor", "Address"),
            ("ctrEmail", "Contractor", "E-mail"),
            ("cliName", "Client", "Client name"),
            ("cliAddr", "Client", "Address"),
        ],
        "yes_flag_label": "Value meaning “billable”",
        "checks": "Checks",
        "check_rows": ["Period", "Log rows in the period", "Log rows outside the period",
                       "Log rows without a rate (rate = 0)"],
        "period_bad": "⚠ “Period to” is earlier than “Period from”",
        "period_ok": "✓ OK",
        "invoice_word": "INVOICE", "no_prefix": "No. ",
        "bill_to": "Bill to", "inv_date": "Invoice date", "due": "Due date",
        "per_from": "Period from", "per_to": "Period to",
        "line_hdr": ["#", "Specialist", "Role", "Hours", "Rate, ", "Amount, "],
        "subtotal": "Subtotal", "tax": "Tax ", "total": "Total, ",
        "by_project": "Billed hours by project", "proj_hdr": ["#", "Project", "", "Hours", "", "Amount, "],
        "check_vs_lines": "Check: project total = invoice subtotal",
        "check_ok": "✓ matches", "check_bad": "✗ differs",
        "note_round": ("Each time entry is rounded up to ", " h (ROUNDUP) before billing."),
        "note_terms": ("Payment due within ", " days of the invoice date."),
        "note_demo": "Demo document generated by build_invoice.py — fictional companies, not a real invoice.",
        "payroll_title": "Payroll for the period",
        "period_caption": "Period: ",
        "pay_hdr": ["Employee", "Role", "Hours worked", "Pay rate, ", "Gross pay, ", "Adjustment, ",
                    "Total pay, ", "Billed hours", "Billed amount, ", "Margin, ", "Utilisation"],
        "pay_note": "Yellow “Adjustment” cells are inputs (bonus + / deduction −). Utilisation = billable ÷ worked hours.",
        "summary_title": "Summary by week",
        "sum_hdr": ["Week", "From", "To", "Hours worked", "Billed hours", "Invoice amount, ",
                    "Payroll cost, ", "Margin, "],
        "sum_check": "Check: weekly total = invoice subtotal",
        "sum_trunc": "⚠ The period is longer than 6 weeks — later weeks are not shown",
        "chart_weeks": "Invoice amount vs payroll cost by week",
        "log_note": "Paste new rows under the table: grey columns are formulas and fill in automatically.",
        "rates_note": "Rates are inputs. A name in WorkLog must match a name here exactly.",
        "total_row": "Total",
        "err_title": "Invalid value", "err_list": "Pick a value from the list.",
    },
    "ru": {
        "sheets": {"invoice": "Счёт", "payroll": "Зарплата", "summary": "Сводка",
                   "log": "Журнал", "rates": "Ставки", "settings": "Настройки"},
        "log_cols": ["Дата", "Сотрудник", "Проект", "Задача", "Часы", "Оплачиваемо", "ЧасыКОплате",
                     "Ставка", "Сумма", "СтавкаЗП", "ЗП"],
        "rate_cols": ["Сотрудник", "Роль", "СтавкаКлиенту", "СтавкаСотруднику"],
        "yes": "Да", "no": "Нет",
        "date_fmt": "dd.mm.yyyy",
        "demo": "Демо-проект · Demo project — компании, люди и цифры вымышлены",
        "settings_title": "Настройки счёта и зарплаты",
        "set_hdr": ["Параметр", "Значение", "Примечание"],
        "set_rows": [
            ("invNo", "Номер счёта", "Печатается в счёте"),
            ("invDate", "Дата счёта", ""),
            ("perFrom", "Период с", "В счёт и зарплату попадают только строки внутри периода"),
            ("perTo", "Период по", "Включительно"),
            ("termsDays", "Срок оплаты, дней", "Оплатить до = дата счёта + срок"),
            ("billInc", "Шаг округления, ч", "Каждая запись округляется ВВЕРХ до шага (0,25 = 15 мин)"),
            ("taxRate", "Ставка налога / НДС", "0%, если не применяется"),
            ("currency", "Валюта", "Подставляется в заголовки"),
        ],
        "parties": [
            ("ctrName", "Исполнитель", "Название"),
            ("ctrAddr", "Исполнитель", "Адрес"),
            ("ctrEmail", "Исполнитель", "E-mail"),
            ("cliName", "Заказчик", "Название"),
            ("cliAddr", "Заказчик", "Адрес"),
        ],
        "yes_flag_label": "Значение «оплачиваемо»",
        "checks": "Проверки",
        "check_rows": ["Период", "Строк журнала в периоде", "Строк журнала вне периода",
                       "Строк без ставки (ставка = 0)"],
        "period_bad": "⚠ «Период по» раньше, чем «Период с»",
        "period_ok": "✓ OK",
        "invoice_word": "СЧЁТ", "no_prefix": "№ ",
        "bill_to": "Заказчик", "inv_date": "Дата счёта", "due": "Оплатить до",
        "per_from": "Период с", "per_to": "Период по",
        "line_hdr": ["№", "Специалист", "Роль", "Часы", "Ставка, ", "Сумма, "],
        "subtotal": "Итого без налога", "tax": "Налог ", "total": "Всего к оплате, ",
        "by_project": "Часы к оплате по проектам", "proj_hdr": ["№", "Проект", "", "Часы", "", "Сумма, "],
        "check_vs_lines": "Проверка: сумма по проектам = итог счёта",
        "check_ok": "✓ совпадает", "check_bad": "✗ расходится",
        "note_round": ("Каждая запись времени округляется вверх до ", " ч (ОКРВВЕРХ / ROUNDUP)."),
        "note_terms": ("Оплата в течение ", " дней с даты счёта."),
        "note_demo": "Демо-документ, создан build_invoice.py — вымышленные компании, не настоящий счёт.",
        "payroll_title": "Зарплата за период",
        "period_caption": "Период: ",
        "pay_hdr": ["Сотрудник", "Роль", "Отработано, ч", "Ставка ЗП, ", "Начислено, ",
                    "Корректировка, ", "К выплате, ", "Часы к оплате", "Выставлено, ", "Маржа, ",
                    "Загрузка"],
        "pay_note": "Жёлтые ячейки «Корректировка» — ввод (премия + / удержание −). Загрузка = оплачиваемые ÷ отработанные часы.",
        "summary_title": "Сводка по неделям",
        "sum_hdr": ["Неделя", "С", "По", "Отработано, ч", "Часы к оплате", "Сумма счёта, ",
                    "Фонд оплаты, ", "Маржа, "],
        "sum_check": "Проверка: итог по неделям = итог счёта",
        "sum_trunc": "⚠ Период длиннее 6 недель — последние недели не показаны",
        "chart_weeks": "Сумма счёта и фонд оплаты по неделям",
        "log_note": "Новые строки вставляйте под таблицей: серые столбцы — формулы и заполнятся сами.",
        "rates_note": "Ставки — поля ввода. Имя в журнале должно точно совпадать с именем здесь.",
        "total_row": "Итого",
        "err_title": "Недопустимое значение", "err_list": "Выберите значение из списка.",
    },
}

PARTIES = {
    "en": {"ctrName": f"{DEMO_CONTRACTOR} (demo)", "ctrAddr": "12 Example Lane, Springfield",
           "ctrEmail": "billing@nimbra.example", "cliName": f"{DEMO_CLIENT} Ltd. (demo)",
           "cliAddr": "400 Sample Road, Rivertown"},
    "ru": {"ctrName": f"{DEMO_CONTRACTOR} (демо)", "ctrAddr": "г. Примерск, ул. Образцовая, 12",
           "ctrEmail": "billing@nimbra.example", "cliName": f"ООО «{DEMO_CLIENT}» (демо)",
           "cliAddr": "г. Условный, Тестовое шоссе, 400"},
}


def _dt(d: date) -> datetime:
    return datetime(d.year, d.month, d.day)


def build_invoice(entries: list[WorkEntry], rates: list[Rate], out_path: str | Path, *,
                  lang: str = "en", period_from: date, period_to: date,
                  invoice_no: str = "2026-09-001", invoice_date: date | None = None,
                  terms_days: int = 14, increment: float = 0.25, tax_rate: float = 0.0,
                  currency: str = "USD") -> Path:
    if not rates:
        raise ValueError("rates table is empty")
    T = L10N[lang]
    S = T["sheets"]
    invoice_date = invoice_date or period_to + timedelta(days=1)

    wb = Workbook()
    ws_set = wb.active
    ws_set.title = S["settings"]
    ws_inv = wb.create_sheet(S["invoice"])
    ws_pay = wb.create_sheet(S["payroll"])
    ws_sum = wb.create_sheet(S["summary"])
    ws_log = wb.create_sheet(S["log"])
    ws_rates = wb.create_sheet(S["rates"])
    wb.move_sheet(ws_set, offset=5)          # Settings last; Invoice opens first

    values = {"invNo": invoice_no, "invDate": _dt(invoice_date), "perFrom": _dt(period_from),
              "perTo": _dt(period_to), "termsDays": terms_days, "billInc": increment,
              "taxRate": tax_rate, "currency": currency, **PARTIES[lang]}
    _rates_sheet(ws_rates, rates, T)
    _log_sheet(wb, ws_log, entries, T)
    _settings_sheet(wb, ws_set, values, T)
    subtotal_cell = _invoice_sheet(ws_inv, rates, entries, T)
    wb.defined_names["invSubtotal"] = DefinedName("invSubtotal", attr_text=f"{quote_sheet(S['invoice'])}!{subtotal_cell}")
    _payroll_sheet(ws_pay, rates, T, lang)
    _summary_sheet(ws_sum, T)

    wb.calculation = CalcProperties(fullCalcOnLoad=True)
    wb.properties.title = f"{T['invoice_word']} {invoice_no}"
    wb.properties.creator = "xldash demo (github.com/sinnercode228)"
    wb.properties.description = T["demo"]
    wb.active = wb.index(ws_inv)
    for ws in wb.worksheets:
        ws.sheet_view.tabSelected = ws is ws_inv
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_path)
    return out_path


# ------------------------------------------------------------------------- tables

def _rates_sheet(ws, rates, T):
    base_sheet(ws, gridlines=True)
    ws.append(T["rate_cols"])
    for r in rates:
        ws.append([r.employee, r.role, r.bill_rate, r.pay_rate])
    last = len(rates) + 1
    tbl = Table(displayName=RATES, ref=f"A1:D{last}")
    tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
    ws.add_table(tbl)
    for row in ws.iter_rows(min_row=2, max_row=last):
        for c in row:
            c.font = font(10)
        for c in row[2:]:
            input_cell(c, fmt="#,##0.00", align="right")
    for c in ws[1]:
        c.font = font(10, True, "FFFFFF")
    set_widths(ws, {"A": 24, "B": 24, "C": 16, "D": 18, "F": 70})
    ws["F1"] = T["rates_note"]
    ws["F1"].font = font(9, color=INK_2, italic=True)
    ws.freeze_panes = "A2"


def _this(col: str) -> str:
    return f"{LOG}[[#This Row],[{col}]]"


def _log_sheet(wb, ws, entries, T):
    base_sheet(ws, gridlines=True)
    cols = T["log_cols"]
    date_c, emp_c, _proj_c, _task_c, hours_c, bill_c, billed_c, rate_c, amount_c, pay_c, cost_c = cols
    rcols = T["rate_cols"]
    calc = {
        billed_c: f"ROUNDUP({_this(hours_c)}/billInc,0)*billInc",
        rate_c: f"IFERROR(INDEX({RATES}[{rcols[2]}],MATCH({_this(emp_c)},{RATES}[{rcols[0]}],0)),0)",
        amount_c: f"IF({_this(bill_c)}=yesFlag,ROUND({_this(billed_c)}*{_this(rate_c)},2),0)",
        pay_c: f"IFERROR(INDEX({RATES}[{rcols[3]}],MATCH({_this(emp_c)},{RATES}[{rcols[0]}],0)),0)",
        cost_c: f"ROUND({_this(hours_c)}*{_this(pay_c)},2)",
    }
    ws.append(cols)
    for e in entries:
        ws.append([_dt(e.date), e.employee, e.project, e.task, e.hours,
                   T["yes"] if e.billable else T["no"],
                   *(f"={calc[c]}" for c in cols[6:])])
    last = max(len(entries), 1) + 1
    tbl = Table(displayName=LOG, ref=f"A1:K{last}")
    tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
    tbl._initialise_columns()                  # openpyxl would name them Column1..; use real headers
    for tc, name in zip(tbl.tableColumns, cols):
        tc.name = name
        if tc.name in calc:
            tc.calculatedColumnFormula = TableFormula(attr_text=calc[tc.name])
    ws.add_table(tbl)
    fmts = [T["date_fmt"], None, None, None, "0.00", None, "0.00", "#,##0.00", "#,##0.00",
            "#,##0.00", "#,##0.00"]
    for row in ws.iter_rows(min_row=2, max_row=last):
        for i, c in enumerate(row):
            c.font = font(10, color=INK_2 if i >= 6 else "0B0B0B")
            if fmts[i]:
                c.number_format = fmts[i]
            if i >= 6:
                c.fill = fill("F1F0EC")
    for c in ws[1]:
        c.font = font(10, True, "FFFFFF")
    set_widths(ws, {"A": 12, "B": 20, "C": 28, "D": 26, "E": 9, "F": 13, "G": 13, "H": 11,
                    "I": 12, "J": 11, "K": 11, "M": 70})
    ws["M1"] = T["log_note"]
    ws["M1"].font = font(9, color=INK_2, italic=True)
    ws.freeze_panes = "A2"
    dv = DataValidation(type="list", formula1=f'"{T["yes"]},{T["no"]}"', allow_blank=False,
                        showErrorMessage=True, errorTitle=T["err_title"], error=T["err_list"])
    ws.add_data_validation(dv)
    dv.add(f"F2:F{last + 500}")
    emp = DataValidation(type="list", formula1="lstEmployees", allow_blank=False,
                         showErrorMessage=True, errorTitle=T["err_title"], error=T["err_list"])
    ws.add_data_validation(emp)
    emp.add(f"B2:B{last + 500}")
    wb.defined_names["lstEmployees"] = DefinedName("lstEmployees", attr_text=f"{RATES}[{rcols[0]}]")


def _settings_sheet(wb, ws, values, T):
    base_sheet(ws)
    set_widths(ws, {"A": 2, "B": 30, "C": 34, "D": 60})
    title_bar(ws, T["settings_title"], 2, 4, subtitle=T["demo"])
    header_row(ws, 4, 2, T["set_hdr"])
    sq = quote_sheet(ws.title)
    r = 5
    row_of = {}
    fmts = {"invDate": "yyyy-mm-dd", "perFrom": "yyyy-mm-dd", "perTo": "yyyy-mm-dd",
            "termsDays": "0", "billInc": "0.00", "taxRate": "0.0%"}
    for name, label, hint in T["set_rows"]:
        body_cell(ws.cell(row=r, column=2, value=label), align="left", bold=True)
        input_cell(ws.cell(row=r, column=3, value=values[name]), fmt=fmts.get(name))
        body_cell(ws.cell(row=r, column=4, value=hint), align="left", color=INK_2)
        wb.defined_names[name] = DefinedName(name, attr_text=f"{sq}!$C${r}")
        row_of[name] = r
        r += 1
    for name, group, label in T["parties"]:
        body_cell(ws.cell(row=r, column=2, value=f"{group}: {label}"), align="left", bold=True)
        input_cell(ws.cell(row=r, column=3, value=values[name]), align="left")
        body_cell(ws.cell(row=r, column=4, value=""), align="left")
        wb.defined_names[name] = DefinedName(name, attr_text=f"{sq}!$C${r}")
        r += 1
    body_cell(ws.cell(row=r, column=2, value=T["yes_flag_label"]), align="left", bold=True)
    body_cell(ws.cell(row=r, column=3, value=T["yes"]), align="center", color=INK_2)
    body_cell(ws.cell(row=r, column=4, value=f'"{T["yes"]}" / "{T["no"]}"'), align="left", color=INK_2)
    wb.defined_names["yesFlag"] = DefinedName("yesFlag", attr_text=f"{sq}!$C${r}")

    inc = DataValidation(type="decimal", operator="between", formula1="0.01", formula2="8",
                         showErrorMessage=True, errorTitle=T["err_title"], error="0.01 – 8")
    tax = DataValidation(type="decimal", operator="between", formula1="0", formula2="1",
                         showErrorMessage=True, errorTitle=T["err_title"], error="0% – 100%")
    for dv in (inc, tax):
        ws.add_data_validation(dv)
    inc.add(f"C{row_of['billInc']}")
    tax.add(f"C{row_of['taxRate']}")

    r += 2
    section_title(ws, r, 2, T["checks"])
    checks = [
        f'=IF(perTo<perFrom,"{T["period_bad"]}","{T["period_ok"]}")',
        f'=COUNTIFS({LOG}[{T["log_cols"][0]}],">="&perFrom,{LOG}[{T["log_cols"][0]}],"<="&perTo)',
        f"=COUNT({LOG}[{T['log_cols'][0]}])-C{r + 2}",
        f"=COUNTIF({LOG}[{T['log_cols'][7]}],0)",
    ]
    for i, (label, formula) in enumerate(zip(T["check_rows"], checks)):
        rr = r + 1 + i
        body_cell(ws.cell(row=rr, column=2, value=label), align="left")
        body_cell(ws.cell(row=rr, column=3, value=formula), "0", align="center")
    ws.conditional_formatting.add(f"C{r + 1}", FormulaRule(formula=["perTo<perFrom"], font=Font(color=BAD, bold=True)))
    ws.conditional_formatting.add(f"C{r + 4}", FormulaRule(formula=[f"C{r + 4}>0"], font=Font(color=BAD, bold=True)))


# ------------------------------------------------------------------------- invoice

def _sumifs(col_sum: str, T, *crit: str, billable: bool = False) -> str:
    d = f"{LOG}[{T['log_cols'][0]}]"
    parts = [f"{LOG}[{col_sum}]", *crit]
    if billable:
        parts += [f"{LOG}[{T['log_cols'][5]}]", "yesFlag"]
    parts += [d, '">="&perFrom', d, '"<="&perTo']
    return f"SUMIFS({','.join(parts)})"


def _invoice_sheet(ws, rates, entries, T):
    base_sheet(ws)
    set_widths(ws, {"A": 2, "B": 5, "C": 30, "D": 22, "E": 11, "F": 16, "G": 16, "H": 2})
    cols = T["log_cols"]
    rc = T["rate_cols"]

    ws["B2"] = "=ctrName"
    ws["B2"].font = font(16, True, HEADER_FILL)
    ws["G2"] = T["invoice_word"]
    ws["G2"].font = font(20, True, HEADER_FILL)
    ws["G2"].alignment = Alignment(horizontal="right")
    ws["B3"] = "=ctrAddr"
    ws["B4"] = "=ctrEmail"
    for a in ("B3", "B4"):
        ws[a].font = font(9, color=INK_2)
    ws["G3"] = f'="{T["no_prefix"]}"&invNo'
    ws["G3"].font = font(11, True)
    ws["G3"].alignment = Alignment(horizontal="right")
    for c in range(2, 8):
        ws.cell(row=5, column=c).border = Border(bottom=Side(style="medium", color=HEADER_FILL))

    ws["B7"] = T["bill_to"]
    ws["B7"].font = font(8, True, MUTED)
    ws["B8"] = "=cliName"
    ws["B8"].font = font(11, True)
    ws["B9"] = "=cliAddr"
    ws["B9"].font = font(9, color=INK_2)
    meta = [(T["inv_date"], "=invDate"), (T["due"], "=invDate+termsDays"),
            (T["per_from"], "=perFrom"), (T["per_to"], "=perTo")]
    for i, (label, formula) in enumerate(meta):
        r = 7 + i
        lab = ws.cell(row=r, column=5, value=label)
        lab.font = font(9, color=INK_2)
        ws.merge_cells(start_row=r, start_column=5, end_row=r, end_column=6)
        v = ws.cell(row=r, column=7, value=formula)
        v.number_format = T["date_fmt"]
        v.font = font(10, True)
        v.alignment = Alignment(horizontal="right")

    hdr = 12
    labels = T["line_hdr"]
    header_row(ws, hdr, 2, labels[:4] + [f'="{labels[4]}"&currency', f'="{labels[5]}"&currency'])
    first = hdr + 1
    for i, rate in enumerate(rates):
        r = first + i
        body_cell(ws.cell(row=r, column=2, value=i + 1), "0", align="center")
        body_cell(ws.cell(row=r, column=3, value=rate.employee), align="left")
        body_cell(ws.cell(row=r, column=4,
                          value=f"=IFERROR(INDEX({RATES}[{rc[1]}],MATCH($C{r},{RATES}[{rc[0]}],0)),\"\")"),
                  align="left", color=INK_2)
        body_cell(ws.cell(row=r, column=5,
                          value=f"={_sumifs(cols[6], T, f'{LOG}[{cols[1]}]', f'$C{r}', billable=True)}"), FMT_H)
        body_cell(ws.cell(row=r, column=6,
                          value=f"=IFERROR(INDEX({RATES}[{rc[2]}],MATCH($C{r},{RATES}[{rc[0]}],0)),0)"),
                  FMT_MONEY)
        body_cell(ws.cell(row=r, column=7, value=f"=ROUND(E{r}*F{r},2)"), FMT_MONEY)
    last = first + len(rates) - 1
    sub, tax, tot = last + 2, last + 3, last + 4
    rows = [(sub, T["subtotal"], f"=SUM(G{first}:G{last})"),
            (tax, f'="{T["tax"]}("&ROUND(taxRate*100,2)&"%)"', f"=ROUND(G{sub}*taxRate,2)"),
            (tot, f'="{T["total"]}"&currency', f"=G{sub}+G{tax}")]
    for r, label, formula in rows:
        lab = ws.cell(row=r, column=5, value=label)
        ws.merge_cells(start_row=r, start_column=5, end_row=r, end_column=6)
        lab.alignment = Alignment(horizontal="right")
        v = ws.cell(row=r, column=7, value=formula)
        v.number_format = FMT_MONEY
        lab.font = v.font = font(10, r == tot)
    ws.cell(row=sub, column=5).font = font(10)
    for c in range(5, 8):
        ws.cell(row=tot, column=c).fill = fill(PANEL)
        ws.cell(row=tot, column=c).border = TOP_DOUBLE
    ws.cell(row=tot, column=7).font = font(12, True, HEADER_FILL)
    ws.cell(row=tot, column=5).font = font(11, True, HEADER_FILL)

    # hours by project
    projects = sorted({e.project for e in entries}, key=str.casefold)
    p0 = tot + 3
    section_title(ws, p0, 2, T["by_project"])
    ph = T["proj_hdr"]
    header_row(ws, p0 + 1, 2, [ph[0], ph[1], ph[2], ph[3], ph[4], f'="{ph[5]}"&currency'])
    ws.merge_cells(start_row=p0 + 1, start_column=3, end_row=p0 + 1, end_column=4)
    pf = p0 + 2
    for i, p in enumerate(projects):
        r = pf + i
        body_cell(ws.cell(row=r, column=2, value=i + 1), "0", align="center")
        body_cell(ws.cell(row=r, column=3, value=p), align="left")
        ws.merge_cells(start_row=r, start_column=3, end_row=r, end_column=4)
        body_cell(ws.cell(row=r, column=5,
                          value=f"={_sumifs(cols[6], T, f'{LOG}[{cols[2]}]', f'$C{r}', billable=True)}"), FMT_H)
        body_cell(ws.cell(row=r, column=6, value=None))
        body_cell(ws.cell(row=r, column=7,
                          value=f"={_sumifs(cols[8], T, f'{LOG}[{cols[2]}]', f'$C{r}')}"), FMT_MONEY)
    pl = pf + len(projects) - 1
    pt = pl + 1
    ws.cell(row=pt, column=3, value=T["total_row"]).font = font(10, True)
    for c, formula, fmt in ((5, f"=SUM(E{pf}:E{pl})", FMT_H), (7, f"=SUM(G{pf}:G{pl})", FMT_MONEY)):
        cell = ws.cell(row=pt, column=c, value=formula)
        cell.number_format = fmt
        cell.font = font(10, True)
    for c in range(2, 8):
        ws.cell(row=pt, column=c).border = TOP_DOUBLE
    chk = pt + 1
    ws.cell(row=chk, column=3, value=T["check_vs_lines"]).font = font(9, color=INK_2)
    ws.cell(row=chk, column=7,
            value=f'=IF(ABS(G{pt}-G{sub})<0.005,"{T["check_ok"]}","{T["check_bad"]}")').font = font(9, True)
    ws.cell(row=chk, column=7).alignment = Alignment(horizontal="right")
    ws.conditional_formatting.add(f"G{chk}", FormulaRule(formula=[f"ABS(G{pt}-G{sub})<0.005"],
                                                         font=Font(color=GOOD, bold=True)))
    ws.conditional_formatting.add(f"G{chk}", FormulaRule(formula=[f"ABS(G{pt}-G{sub})>=0.005"],
                                                         font=Font(color=BAD, bold=True)))

    n0 = chk + 2
    notes = [f'="{T["note_round"][0]}"&billInc&"{T["note_round"][1]}"',
             f'="{T["note_terms"][0]}"&termsDays&"{T["note_terms"][1]}"',
             T["note_demo"]]
    for i, text in enumerate(notes):
        c = ws.cell(row=n0 + i, column=2, value=text)
        c.font = font(8, color=MUTED, italic=True)

    last_row = n0 + len(notes)
    ws.print_area = f"A1:H{last_row}"
    ws.page_setup.paperSize = ws.PAPERSIZE_A4
    ws.page_setup.orientation = "portrait"
    ws.page_setup.fitToWidth = 1
    ws.page_setup.fitToHeight = 1
    ws.sheet_properties.pageSetUpPr.fitToPage = True
    ws.print_options.horizontalCentered = True
    ws.page_margins.left = ws.page_margins.right = 0.5
    ws.page_margins.top = ws.page_margins.bottom = 0.6
    ws.oddFooter.center.text = "&8" + T["demo"]
    ws.oddFooter.right.text = "&8&P / &N"
    return f"$G${sub}"


# ------------------------------------------------------------------------- payroll

def _payroll_sheet(ws, rates, T, lang):
    base_sheet(ws)
    set_widths(ws, {"A": 2, "B": 22, "C": 20, "D": 12, "E": 12, "F": 13, "G": 14, "H": 13,
                    "I": 12, "J": 14, "K": 13, "L": 11})
    title_bar(ws, T["payroll_title"], 2, 12, subtitle=T["demo"])
    ws["B3"] = f'="{T["period_caption"]}"&{date_text("perFrom", lang)}&" – "&{date_text("perTo", lang)}'
    ws["B3"].font = font(10, True, INK_2)
    cols, rc = T["log_cols"], T["rate_cols"]
    hdr = [h if not h.endswith(", ") else f'="{h}"&currency' for h in T["pay_hdr"]]
    header_row(ws, 5, 2, hdr)
    first = 6
    for i, rate in enumerate(rates):
        r = first + i
        emp = (f"{LOG}[{cols[1]}]", f"$B{r}")
        body_cell(ws.cell(row=r, column=2, value=rate.employee), align="left")
        body_cell(ws.cell(row=r, column=3,
                          value=f'=IFERROR(INDEX({RATES}[{rc[1]}],MATCH($B{r},{RATES}[{rc[0]}],0)),"")'),
                  align="left", color=INK_2)
        body_cell(ws.cell(row=r, column=4, value=f"={_sumifs(cols[4], T, *emp)}"), FMT_H)
        body_cell(ws.cell(row=r, column=5,
                          value=f"=IFERROR(INDEX({RATES}[{rc[3]}],MATCH($B{r},{RATES}[{rc[0]}],0)),0)"), FMT_MONEY)
        body_cell(ws.cell(row=r, column=6, value=f"={_sumifs(cols[10], T, *emp)}"), FMT_MONEY)
        input_cell(ws.cell(row=r, column=7, value=0), fmt=FMT_MONEY, align="right")
        body_cell(ws.cell(row=r, column=8, value=f"=F{r}+G{r}"), FMT_MONEY, bold=True)
        body_cell(ws.cell(row=r, column=9, value=f"={_sumifs(cols[6], T, *emp, billable=True)}"), FMT_H)
        body_cell(ws.cell(row=r, column=10, value=f"={_sumifs(cols[8], T, *emp)}"), FMT_MONEY)
        body_cell(ws.cell(row=r, column=11, value=f"=J{r}-H{r}"), FMT_MONEY)
        body_cell(ws.cell(row=r, column=12,
                          value=f'=IF(D{r}=0,"",{_sumifs(cols[4], T, *emp, billable=True)}/D{r})'), FMT_PCT)
    last = first + len(rates) - 1
    tot = last + 1
    for c in range(2, 13):
        cell = ws.cell(row=tot, column=c)
        cell.border = TOP_DOUBLE
        cell.fill = fill(PANEL)
        cell.font = font(10, True)
    ws.cell(row=tot, column=2, value=T["total_row"])
    for c, fmt in ((4, FMT_H), (6, FMT_MONEY), (7, FMT_MONEY), (8, FMT_MONEY), (9, FMT_H),
                   (10, FMT_MONEY), (11, FMT_MONEY)):
        letter = ws.cell(row=tot, column=c).column_letter
        cell = ws.cell(row=tot, column=c, value=f"=SUM({letter}{first}:{letter}{last})")
        cell.number_format = fmt
    ws.cell(row=tot, column=12,
            value=f'=IF(D{tot}=0,"",{_sumifs(cols[4], T, billable=True)}/D{tot})').number_format = FMT_PCT
    ws.cell(row=tot + 2, column=2, value=T["pay_note"]).font = font(9, color=INK_2, italic=True)
    ws.conditional_formatting.add(f"K{first}:K{tot}", FormulaRule(formula=[f"K{first}<0"],
                                                                   font=Font(color=BAD, bold=True)))
    ws.print_area = f"A1:L{tot + 2}"
    ws.page_setup.orientation = "landscape"
    ws.page_setup.paperSize = ws.PAPERSIZE_A4
    ws.page_setup.fitToWidth = 1
    ws.page_setup.fitToHeight = 0
    ws.sheet_properties.pageSetUpPr.fitToPage = True
    ws.freeze_panes = "C6"


# ------------------------------------------------------------------------- weekly summary

def _summary_sheet(ws, T):
    base_sheet(ws)
    set_widths(ws, {"A": 2, "B": 9, "C": 13, "D": 13, "E": 14, "F": 14, "G": 16, "H": 16, "I": 14})
    title_bar(ws, T["summary_title"], 2, 9, subtitle=T["demo"])
    cols = T["log_cols"]
    d = f"{LOG}[{cols[0]}]"
    hdr = [h if not h.endswith(", ") else f'="{h}"&currency' for h in T["sum_hdr"]]
    header_row(ws, 4, 2, hdr)
    first = 5
    for w in range(WEEKS):
        r = first + w
        start = "=perFrom" if w == 0 else f'=IF(C{r - 1}="","",IF(D{r - 1}+1>perTo,"",D{r - 1}+1))'
        rng = f'{d},">="&$C{r},{d},"<="&$D{r}'
        body_cell(ws.cell(row=r, column=2, value=f'=IF(C{r}="","",{w + 1})'), "0", align="center")
        body_cell(ws.cell(row=r, column=3, value=start), T["date_fmt"], align="center")
        body_cell(ws.cell(row=r, column=4, value=f'=IF(C{r}="","",MIN(perTo,C{r}+7-WEEKDAY(C{r},2)))'),
                  T["date_fmt"], align="center")
        body_cell(ws.cell(row=r, column=5, value=f'=IF(C{r}="","",SUMIFS({LOG}[{cols[4]}],{rng}))'), FMT_H)
        body_cell(ws.cell(row=r, column=6,
                          value=f'=IF(C{r}="","",SUMIFS({LOG}[{cols[6]}],{LOG}[{cols[5]}],yesFlag,{rng}))'), FMT_H)
        body_cell(ws.cell(row=r, column=7, value=f'=IF(C{r}="","",SUMIFS({LOG}[{cols[8]}],{rng}))'), FMT_MONEY)
        body_cell(ws.cell(row=r, column=8, value=f'=IF(C{r}="","",SUMIFS({LOG}[{cols[10]}],{rng}))'), FMT_MONEY)
        body_cell(ws.cell(row=r, column=9, value=f'=IF(C{r}="","",G{r}-H{r})'), FMT_MONEY)
    last = first + WEEKS - 1
    tot = last + 1
    for c in range(2, 10):
        cell = ws.cell(row=tot, column=c)
        cell.border = TOP_DOUBLE
        cell.fill = fill(PANEL)
        cell.font = font(10, True)
    ws.cell(row=tot, column=2, value=T["total_row"])
    for c, fmt in ((5, FMT_H), (6, FMT_H), (7, FMT_MONEY), (8, FMT_MONEY), (9, FMT_MONEY)):
        letter = ws.cell(row=tot, column=c).column_letter
        cell = ws.cell(row=tot, column=c, value=f"=SUM({letter}{first}:{letter}{last})")
        cell.number_format = fmt
    chk = tot + 1
    ws.cell(row=chk, column=2, value=T["sum_check"]).font = font(9, color=INK_2)
    ws.cell(row=chk, column=7,
            value=f'=IF(ABS(G{tot}-invSubtotal)<0.005,"{T["check_ok"]}","{T["check_bad"]}")').font = font(9, True)
    ws.conditional_formatting.add(f"G{chk}", FormulaRule(formula=[f'LEFT(G{chk},1)="✓"'],
                                                         font=Font(color=GOOD, bold=True)))
    ws.conditional_formatting.add(f"G{chk}", FormulaRule(formula=[f'LEFT(G{chk},1)="✗"'],
                                                         font=Font(color=BAD, bold=True)))
    ws.cell(row=chk + 1, column=2,
            value=f'=IF(AND(ISNUMBER(D{last}),D{last}<perTo),"{T["sum_trunc"]}","")').font = font(9, True, BAD)

    ch = BarChart()
    ch.add_data(Reference(ws, min_col=7, max_col=8, min_row=4, max_row=last), titles_from_data=True)
    ch.set_categories(Reference(ws, min_col=3, min_row=first, max_row=last))
    style_bar_chart(ch, T["chart_weeks"], horizontal=False, colors=(BLUE, ORANGE), width=17, height=8,
                    number_format="#,##0")
    ch.x_axis.number_format = T["date_fmt"]
    ch.x_axis.auto = False             # text categories: one slot per week, not a calendar axis
    ws.add_chart(ch, f"B{chk + 3}")
    ws.print_area = f"A1:I{chk + 20}"
    ws.page_setup.orientation = "landscape"
    ws.page_setup.fitToWidth = 1
    ws.sheet_properties.pageSetUpPr.fitToPage = True
